# Site settings
title: Tyler Campbell
description: Tyler Campbell makes things for the Internet.
url: "http://tyler.camp" # the base hostname & protocol for your site

# Exclude
exclude: [node_modules, gulpfile.js]
