# Site settings
title: Tyler Campbell
description: Tyler Campbell makes things for the Internet.
url: "http://tyler.camp"

# Sass
sass:
  sass_dir: assets/sass
  style: compressed

# Exclude
exclude: [__source, CNAME, gulpfile.js, node_modules]
